name: kumsap_marketplace
description: Kum-Sap Marketplace is a simple online shopping application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_hooks: 0.18.5+1
  hooks_riverpod: ^2.0.2
  font_awesome_flutter: ^10.2.1
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  status_bar_control: ^3.2.1
  flex_color_scheme: ^5.1.0
  flutter_svg: ^1.1.5
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_slidable: ^2.0.0
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: IBMPlexSansThai
      fonts:
        - asset: assets/fonts/IBMPlexSansThai/IBMPlexSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansThai/IBMPlexSansThai-SemiBold.ttf
          weight: 600
  
  assets:
    - assets/images/svg/
    - assets/mock/product.json
